name: Pipeline automated tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install frontend modules
      run: npm run install:frontend
    - name: Run frontend unit tests 🧪
      run: npm run test:frontend:unit
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Backend modules
        uses: cypress-io/github-action@v5
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install Frontend modules
        uses: cypress-io/github-action@v5
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run API tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:frontend, npm run start:server
          command: npm run test:api
  frontend-tests:
    needs: frontend-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Frontend modules
        uses: cypress-io/github-action@v5
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run Frontend UI tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:frontend
          command: npm run test:frontend
  slack-report:
    name: Post report slack
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs:
      frontend-tests
    steps:
      name: Send slack message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'qa_team'
        slack-message: 'Results of tests in sandbox:dancy_cucumber:'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TEST_TOKEN }}
